apiVersion: v1
kind: Service
metadata:
  name: mc01
  labels: {{- include "vprofile.labels" . | nindent 4 }}
spec:
  selector:
    app: mc01
  ports:
    - name: memcached
      port: 11211
      targetPort: 11211
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc01
  labels: {{- include "vprofile.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc01
  template:
    metadata:
      labels:
        app: mc01
        {{- include "vprofile.labels" . | nindent 8 }}
    spec:
      {{- if $.Values.serviceAccounts.enabled }}
      serviceAccountName: mc01
      {{- end }}
      containers:
        - name: memcached
          image: {{ include "vprofile.image" (dict "root" . "name" "vprofile-mc") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 11211
          readinessProbe:
            tcpSocket: { port: 11211 }
            initialDelaySeconds: 5
          securityContext:
            {{- include "vprofile.containerSecurity" (dict "root" . "extra" .Values.securityContext.mc) | nindent 12 }}
          resources: {{- toYaml .Values.memcached.resources | nindent 12 }}
